- name: Instalar paquetes con loop
  hosts: all
  become: true
  tasks:
    - name: Instalar paquetes
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - curl
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - glances
        - git
        - vim