---
- name: Playbook2 ejercicio1
  hosts: all
  become: true
  user: node
  tasks:
    - name: Instalar apache
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: Guardar fecha en /tmp/fechahora.data
      ansible.builtin.shell:
        cmd: date > /tmp/fechahora.data
...      
