---
- name: Playbook3 ejercicio1
  hosts: all
  become: true
  user: node
  tasks:
    - name: Instalar apache
      apt:
        name: apache2
        state: present
    - name: Guardar fecha en /tmp/fechahora.data
      shell: date > /tmp/fechahora.data
    - name: Comprobar que apache se ha instalado
      shell: apache2 -v
    - name: Instalar mariadb
      apt:
        name: mariadb-server
        state: latest
...      
